'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {ArrowUpRight,ArrowRight,Compass,Newspaper,Heart,Users,Monitor,RefreshCw} from 'lucide-react';
import BrandMark from '../brand-mark';
import {LocalTimestamp,LocalToday} from '../device-time';
import {TOPICS,type NewsData} from '@/lib/news';
export default function Explore({initial,preview=true}:{initial:NewsData;preview?:boolean}){
 const [data,setData]=useState(initial),[topic,setTopic]=useState('All stories'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[limit,setLimit]=useState(6);
 const stories=data.stories.filter(s=>topic==='All stories'||s.topics.includes(topic as typeof TOPICS[number]));
 const lead=data.stories.find(s=>s.image)||data.stories[0];
 const refreshing=useRef(false);const refresh=useCallback(async()=>{if(refreshing.current)return;refreshing.current=true;setBusy(true);try{const r=await fetch('/api/news');if(!r.ok)throw Error();setData(await r.json());setMessage('Headlines refreshed.');}catch{setMessage('Could not refresh. Your last available stories are still here.');}finally{refreshing.current=false;setBusy(false);}},[]);
 useEffect(()=>{try{const saved=localStorage.getItem('harbor-explore-topic');if(saved==='All stories'||TOPICS.includes(saved as typeof TOPICS[number]))setTopic(saved!);}catch{}const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh();},300000);return()=>window.clearInterval(timer);},[refresh]);
 return <div className="eg">{preview&&<div className="eg-preview">DESIGN PREVIEW · EXPLORE & GROW <a href="/">Compare current design ↗</a></div>}<div className="eg-shell">
 <header className="eg-header"><a href={preview?"/explore-preview":"/"} className="site-brand eg-brand"><BrandMark/><span>My Day Harbor</span></a><nav aria-label="Main navigation"><a href="#stories">News</a><a href="/wellness">Fitness & Nutrition</a><a href="/communities">Communities</a><a href="/local-help">Local Tech Help</a></nav><a className="eg-account" href="/account">My account <ArrowUpRight size={15}/></a></header>
 <main><section className="eg-intro"><div><p className="eg-kicker"><span/> IDEAS. WELLBEING. A LITTLE FORWARD MOTION.</p><h1>Explore and <em>grow.</em></h1><p>A wider view of the world. A healthier everyday.<br/>Find something that moves you forward.</p></div><div className="eg-date"><LocalToday/><span>Your next chapter starts here.</span></div></section>
 <section className="eg-feature-grid" aria-label="Featured discoveries">
 {lead?<a className="eg-lead" href={lead.url} target="_blank" rel="noopener noreferrer">{lead.image&&<img src={lead.image.url} alt="" onError={e=>{e.currentTarget.style.display='none';}}/>}<div className="eg-lead-shade"/><div className="eg-lead-copy"><span className="eg-pill">IN THE WORLD · {lead.topics[0]}</span><h2>{lead.title}</h2><div className="eg-lead-bottom"><span>{lead.source} · <LocalTimestamp value={lead.published}/></span><span className="eg-round"><ArrowUpRight size={21}/></span></div></div></a>:<div className="eg-lead eg-fallback"><Compass size={48}/><h2>A little curiosity goes a long way.</h2><p>Headlines will appear when publishers are available.</p><button onClick={refresh}>Try again</button></div>}
 <div className="eg-side"><a href="/wellness" className="eg-wellness" aria-label="Explore Fitness and Nutrition"><div className="eg-wellness-photos"><figure><img src="https://images.pexels.com/photos/25004923/pexels-photo-25004923/free-photo-of-salad-in-bowl.jpeg?auto=compress&cs=tinysrgb&w=700" alt="Colorful vegetable bowl"/><figcaption>Food that fuels you</figcaption></figure><figure><img src="https://images.pexels.com/photos/14019121/pexels-photo-14019121.jpeg?auto=compress&cs=tinysrgb&w=700" alt="A man and woman doing a partner plank workout in a gym"/><figcaption>Movement for your day</figcaption></figure></div><div className="eg-wellness-copy"><p className="eg-kicker">FITNESS & NUTRITION</p><h2>Eat well. Move more.<br/>Make it your own.</h2><p>Plan your portions, explore nutrient estimates, and build a workout routine that fits your day.</p><span className="eg-textlink">Explore your wellbeing <ArrowUpRight size={17}/></span></div></a><a href="/communities" className="eg-community"><span className="eg-icon"><Users size={24}/></span><div><p className="eg-kicker">IDEAS INTO ACTION</p><h2>Find your people.<br/>Build what’s next.</h2><p>Startup guides, communities, and a place to begin.</p></div><ArrowUpRight size={22}/></a></div></section>
 <section className="eg-stories" id="stories"><div className="eg-section-heading"><div><p className="eg-kicker">FOLLOW YOUR CURIOSITY</p><h2>More to explore</h2></div><button className="eg-refresh" onClick={refresh} disabled={busy}><RefreshCw size={16}/>{busy?'Refreshing…':'Refresh stories'}</button></div><div className="eg-filters" aria-label="Filter news topics">{['All stories',...TOPICS].map(t=><button key={t} aria-pressed={topic===t} onClick={()=>{setTopic(t);setLimit(6);try{localStorage.setItem('harbor-explore-topic',t);}catch{}}}>{t}</button>)}</div><p className="eg-status" role="status">{message|| (data.stale?'Showing the last available headlines.':'Stories from their original publishers.')} {data.unavailable.length>0&&' Some feeds are temporarily unavailable.'}</p><div className="eg-story-grid">{stories.slice(0,limit).map(s=><article key={s.id}><a className="eg-story-image" href={s.url} target="_blank" rel="noopener noreferrer">{s.image?<img src={s.image.url} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none';}}/>:<Newspaper size={36}/>}</a><div className="eg-story-body"><p className="eg-kicker">{s.topics[0]}</p><a href={s.url} target="_blank" rel="noopener noreferrer"><h3>{s.title}</h3></a><div className="eg-source"><span>{s.source}</span><ArrowUpRight size={16}/></div><LocalTimestamp value={s.published}/></div></article>)}</div>{!stories.length&&<p className="eg-empty">No stories for this topic right now. Try another topic or refresh.</p>}{stories.length>limit&&<button className="eg-more" onClick={()=>setLimit(n=>n+6)}>A little more inspiration <ArrowRight size={18}/></button>}</section>
 <a href="/local-help" className="eg-local"><span className="eg-icon"><Monitor size={27}/></span><div><p className="eg-kicker">A HELPING HAND, CLOSE TO HOME</p><h2>Technology should make life easier.</h2><p>Explore local tech help and practical support.</p></div><span className="eg-textlink">Find local help <ArrowUpRight size={20}/></span></a></main>
 <footer className="eg-footer"><span>My Day Harbor</span><p>Your world. Your wellbeing. Your next step.</p><a href="#stories">Keep exploring ↑</a></footer></div><nav className="eg-mobile" aria-label="Mobile navigation"><a href={preview?"/explore-preview":"/"} aria-current="page"><Compass size={20}/>Explore</a><a href="#stories"><Newspaper size={20}/>News</a><a href="/wellness"><Heart size={20}/>Wellbeing</a><a href="/communities"><Users size={20}/>Community</a></nav></div>;
}
