'use client';
import {useEffect,useState,useRef} from 'react';
import {flushSync} from 'react-dom';
import {LocalTimestamp,LocalToday} from '@/app/device-time';
import {Sun,ArrowUpRight,RotateCw,SlidersHorizontal,Sparkles,Globe2,Cpu,TrendingUp,Utensils,Newspaper,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {TOPICS,type Topic,type NewsData,type Story} from '@/lib/news';
import {ArticleImage} from '@/app/newsroom';
const icons={World:Globe2,Technology:Cpu,AI:Sparkles,'U.S. markets':TrendingUp,'India markets':TrendingUp};
const sections=['For you',...TOPICS];
const palettes=[{id:'oat',name:'Light oat',swatch:'#e2d4bb'},{id:'cream',name:'Oat cream',swatch:'#e8ddc7'},{id:'stone',name:'Oat stone',swatch:'#d9d3c8'},{id:'biscuit',name:'Oat biscuit',swatch:'#dfcdb3'}];
function NewsCard({story,featured=false}:{story:Story;featured?:boolean}){return <article className={`${featured?'op-feature':'op-news-card'}${story.image?'':' op-without-image'}`}>
  <ArticleImage story={story} lead={featured}/>
  <div className="op-card-copy"><div className="op-story-meta"><span>{story.topics[0]}</span><a href={story.sourceUrl} target="_blank" rel="noopener noreferrer">{story.source}</a></div><a className="op-headline" href={story.url} target="_blank" rel="noopener noreferrer"><h2>{story.title}</h2></a><div className="op-card-bottom"><LocalTimestamp value={story.published}/><a href={story.url} target="_blank" rel="noopener noreferrer" aria-label={`Read ${story.title}`}><span>Read story</span><ArrowUpRight size={17} aria-hidden="true"/></a></div></div>
</article>;}
export default function DaylightNews({initial,preview=true}:{initial:NewsData;preview?:boolean}){
  const [preferencesReady,setPreferencesReady]=useState(false);
  const homeHref=preview?'/design-preview':'/';
  const [palette,setPalette]=useState('cream');
  const [wide,setWide]=useState(false);
  useEffect(()=>{const query=window.matchMedia('(min-width: 761px)');const sync=()=>setWide(query.matches);sync();query.addEventListener('change',sync);return()=>query.removeEventListener('change',sync);},[]);
  const [data,setData]=useState(initial),[active,setActive]=useState('For you'),[interests,setInterests]=useState<Topic[]>([...TOPICS]),[limit,setLimit]=useState(7),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const matching=data.stories.filter(story=>story.topics.some(topic=>active==='For you'?interests.includes(topic):topic===active));
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('daylight-topics')||'null');if(Array.isArray(saved)&&saved.some(t=>TOPICS.includes(t)))setInterests(saved.filter(t=>TOPICS.includes(t)));}catch{}setPreferencesReady(true);},[]);
  useEffect(()=>{if(preferencesReady&&!preview)try{localStorage.setItem('daylight-topics',JSON.stringify(interests));}catch{}},[interests,preferencesReady,preview]);
  async function refresh(){setBusy(true);setNotice('');try{const response=await fetch('/api/news');if(!response.ok)throw Error();const next:NewsData=await response.json();setData(next);setNotice(next.stale?'Showing the last available headlines.':next.unavailable.length?'Available headlines refreshed. Some publishers are temporarily unavailable.':'Your headlines are up to date.');}catch{setNotice('Could not refresh right now. Your last headlines are still here.');}finally{setBusy(false);}}
  useEffect(()=>{const id=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh();},300000);return()=>window.clearInterval(id);},[]);
  function toggle(topic:Topic){setInterests(current=>current.includes(topic)?current.length>1?current.filter(t=>t!==topic):current:[...current,topic]);setLimit(7);}
  const current=useRef({matching,topics:interests,active});current.current={matching,topics:interests,active};
  useEffect(()=>{
    if(preview)return;
    type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
    const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const definitions:Tool[]=[{name:'read_current_news',title:'Read current headlines',description:'Read headlines in the selected news tab with their original publisher links and publication times.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return{tab:current.current.active,stories:current.current.matching.slice(0,12)};}},{name:'set_news_interests',title:'Set news interests',description:'Replace the selected topic preferences and show the personalized For you feed. Preferences are saved in this browser.',inputSchema:{type:'object',properties:{topics:{type:'array',items:{type:'string',enum:[...TOPICS]},minItems:1,uniqueItems:true}},required:['topics'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||!('topics' in input)||!Array.isArray(input.topics)||input.topics.length===0||input.topics.some(t=>!TOPICS.includes(t))||Object.keys(input).some(k=>k!=='topics'))throw Error('Select at least one valid news topic.');const selected=[...new Set(input.topics)] as Topic[];flushSync(()=>{setInterests(selected);setActive('For you');setLimit(7);});return{topics:selected,tab:'For you'};}}];
    for(const tool of definitions)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[preview]);
  return <div className="original-daylight op-palette-scope" data-palette={palette}>{preview&&<div className="op-preview-strip"><span>Original layout preview</span><a href="/">Compare with current layout <ArrowUpRight size={14}/></a></div>}
  <div className="op-shell">{preview&&<div className="op-palette-bar"><span id="op-palette-label">Try a color</span><RadioGroup value={palette} onValueChange={setPalette} aria-labelledby="op-palette-label" className="op-palette-options">{palettes.map(option=><label key={option.id} className="op-palette-choice" data-selected={palette===option.id}><RadioGroupItem value={option.id} aria-label={option.name}/><span className="op-palette-swatch" style={{background:option.swatch}} aria-hidden="true"/><span>{option.name}</span></label>)}</RadioGroup></div>}<header className="op-header"><a className="op-logo" href={homeHref}><Sun size={31} strokeWidth={2}/><span>daylight<span>.</span></span></a><nav aria-label="Main navigation" className="op-app-nav"><a href={homeHref} aria-current="page"><Newspaper size={17}/>News</a><a href="/wellness"><Utensils size={17}/>Meals &amp; Fitness</a></nav><Dialog><DialogTrigger asChild><Button variant="outline" className="op-interests"><SlidersHorizontal size={16}/><span>Your interests</span></Button></DialogTrigger><DialogContent className="op-palette-dialog op-palette-scope" data-palette={palette}><DialogHeader><DialogTitle>What interests you?</DialogTitle><DialogDescription>{preview?'Choose topics for this preview. Your current website preferences stay as they are.':'Choose at least one topic. Your interests are saved in this browser.'}</DialogDescription></DialogHeader><div className="topic-options">{TOPICS.map(topic=><label key={topic}><Checkbox checked={interests.includes(topic)} disabled={interests.length===1&&interests.includes(topic)} onCheckedChange={()=>toggle(topic)}/><span>{topic}</span></label>)}</div></DialogContent></Dialog></header>
  <main><div className="op-intro"><div><p className="op-eyebrow"><LocalToday/></p><h1>Your world, in focus<span>.</span></h1></div><Button variant="ghost" onClick={refresh} disabled={busy} className="op-refresh"><RotateCw size={16} className={busy?'spinning':''}/>{busy?'Refreshing':'Refresh'}</Button></div>
  <Tabs orientation={wide?'vertical':'horizontal'} value={active} onValueChange={value=>{setActive(value);setLimit(7);}} className="op-layout"><aside className="op-topics"><span className="op-eyebrow">Explore</span><TabsList className="op-topic-list">{sections.map(topic=>{const Icon=topic==='For you'?Sparkles:icons[topic as Topic];return <TabsTrigger key={topic} value={topic}><Icon size={17}/><span>{topic}</span></TabsTrigger>;})}</TabsList><div className="op-sidebar-note"><Sun size={22}/><p>A little perspective.<br/>Room for your day.</p></div></aside>
  <div className="op-feed"><div className="op-feed-heading"><h2>{active==='For you'?'Picked by your interests':active}</h2><span>Latest first</span></div>{!preview&&<p className="op-freshness">Refreshes every 5 minutes · {data.stale?'Last successful update':'Checked'} <LocalTimestamp value={data.checkedAt}/></p>}{data.stale&&!notice&&<p className="op-notice" role="status">Showing the last available headlines while publisher feeds recover.</p>}{notice&&<p className="op-notice" role="status">{notice}</p>}{data.unavailable.length>0&&<p className="op-notice" role="status">Some publishers are temporarily unavailable: {data.unavailable.join(', ')}. Available stories are shown below.</p>}{sections.map(section=><TabsContent key={section} value={section} className="op-panel">{matching.length?<><NewsCard story={matching[0]} featured/><div className="op-more-heading"><h2>Worth a look</h2><span>{Math.max(0,matching.length-1)} more stories</span></div><div className="op-card-grid">{matching.slice(1,limit).map(story=><NewsCard key={story.id} story={story}/>)}</div>{matching.length>limit?<Button variant="outline" className="op-load" onClick={()=>setLimit(n=>n+6)}>More stories <ArrowUpRight size={16}/></Button>:<p className="op-caught-up"><Check size={17}/>You’re caught up.</p>}</>:<div className="op-empty"><Globe2 size={29}/><h2>{data.stories.length?'No matching headlines right now.':'The news is taking a moment.'}</h2><p>{data.stories.length?'Try another topic or refresh the feed.':'The publisher feeds could not be reached. Please try refreshing.'}</p><Button variant="outline" className="op-load" onClick={refresh} disabled={busy}>Try again</Button></div>}</TabsContent>)}</div></Tabs></main>
  <footer className="op-footer"><span>daylight.</span><p>Stories and images from their original publishers.</p>{preview&&<a href="/">Current layout <ArrowUpRight size={14}/></a>}</footer></div></div>;
}
