export type CommunityResource={id:string;name:string;organization:string;description:string;url:string;region:'Worldwide'|'India'|'United States';format:'Online'|'In person & online';focus:'Co-founders'|'Mentoring'|'Events'|'Learning'|'Launch & feedback';access:string;note:string;initials:string};
export const COMMUNITIES:CommunityResource[]=[
 {id:'startup-school',name:'Startup School',organization:'Y Combinator',description:'Learn alongside a worldwide community of people turning an idea into a startup.',url:'https://www.startupschool.org/',region:'Worldwide',format:'Online',focus:'Learning',access:'Free · account signup',note:'A self-paced course for aspiring and early-stage founders.',initials:'YC'},
 {id:'yc-matching',name:'Co-Founder Matching',organization:'Y Combinator',description:'Meet potential co-founders with complementary interests, ambitions, and skills.',url:'https://www.ycombinator.com/cofounder-matching',region:'Worldwide',format:'Online',focus:'Co-founders',access:'Free · profile & approval required',note:'For finding co-founders. Profiles stay within YC’s approved community.',initials:'YC'},
 {id:'startup-grind',name:'Startup Grind events',organization:'Startup Grind',description:'Find local startup talks, product demos, and opportunities to meet other builders.',url:'https://www.startupgrind.com/events/',region:'Worldwide',format:'In person & online',focus:'Events',access:'Registration and price vary',note:'Choose a location on the original website and check the next event.',initials:'SG'},
 {id:'score',name:'Find a business mentor',organization:'SCORE',description:'Talk through a business idea or a current challenge with an experienced volunteer mentor.',url:'https://www.score.org/how-mentoring-works/',region:'United States',format:'In person & online',focus:'Mentoring',access:'Free · mentoring request required',note:'For aspiring or established owners of a U.S.-based business.',initials:'SC'},
 {id:'tie',name:'Find a TiE chapter',organization:'TiE Global',description:'Explore an established entrepreneurship network and find a chapter in India or another part of the world.',url:'https://tie.org/our-chapters/',region:'Worldwide',format:'In person & online',focus:'Mentoring',access:'Membership rules and fees vary',note:'Open the local chapter’s site for its programs, events, and membership options.',initials:'TiE'},
 {id:'techstars',name:'Techstars startup events',organization:'Techstars',description:'Browse founder events and Startup Weekends where participants pitch ideas and build with a team.',url:'https://www.techstars.com/events/search',region:'Worldwide',format:'In person & online',focus:'Events',access:'Check each event’s requirements & fees',note:'Startup Weekend is a three-day format. Confirm upcoming dates and location with the organizer.',initials:'TS'},
 {id:'product-hunt',name:'Launch on Product Hunt',organization:'Product Hunt',description:'Explore a product community, prepare a launch, and learn how to collect feedback from early users.',url:'https://www.producthunt.com/launch',region:'Worldwide',format:'Online',focus:'Launch & feedback',access:'Free guide · account needed to submit',note:'New accounts currently need to wait one week before posting a product. Check the current submission rules.',initials:'PH'},
 {id:'startup-india',name:'Startup India Learning Program',organization:'Startup India',description:'Build a foundation in idea assessment, business planning, and starting a business in India.',url:'https://www.startupindia.gov.in/content/sih/en/learning-and-development_v2.html',region:'India',format:'Online',focus:'Learning',access:'Free · registration required',note:'Four-week course in English or Hindi. Best on a laptop: the program’s FAQ says mobile browsers are unsupported.',initials:'SI'}
];
export type Guide={id:string;title:string;organization:string;description:string;url:string;stage:string;note:string};
export const GUIDES:Guide[]=[
 {id:'problems',title:'Requests for Startups',organization:'Y Combinator',description:'Explore problems YC would like founders to tackle, then investigate whether customers actually need a solution.',url:'https://www.ycombinator.com/rfs',stage:'Find a problem',note:'Idea prompts reflect YC’s interests, not validated customer demand.'},
 {id:'business-plan',title:'Plan your business',organization:'U.S. Small Business Administration',description:'Research your market, outline a plan, and estimate the costs of starting.',url:'https://www.sba.gov/counseling/plan-your-business/',stage:'Validate & plan',note:'Public guidance with U.S. business context.'},
 {id:'learn-build',title:'Startup School',organization:'Y Combinator',description:'Learn the fundamentals of building an initial product, finding users, and growing a startup.',url:'https://www.startupschool.org/',stage:'Build & launch',note:'Free, self-paced, worldwide. Signup offered.'},
 {id:'startup-india-guide',title:'Startup India Learning Program',organization:'Startup India',description:'Learn idea assessment, business planning, and startup fundamentals with India-focused examples.',url:'https://www.startupindia.gov.in/content/sih/en/learning-and-development_v2.html',stage:'Validate & plan',note:'Free registration; English or Hindi. The provider recommends a laptop rather than a mobile browser.'},
 {id:'launch-guide',title:'Product Hunt Launch Guide',organization:'Product Hunt',description:'Prepare your product page, plan a launch, and learn what to do before and after sharing your product.',url:'https://www.producthunt.com/launch',stage:'Build & launch',note:'Free public guide. Product submission needs an account and has separate eligibility rules.'},
 {id:'marketing',title:'Inbound Marketing Certification',organization:'HubSpot Academy',description:'Learn customer research, useful content, distribution, and ways to measure marketing results.',url:'https://academy.hubspot.com/courses/inbound-marketing',stage:'Find customers',note:'Free course with a HubSpot Academy account. Multiple languages available.'}
];
export const JOURNEY=[
 {name:'Find a problem',short:'Discover',question:'Who needs something to work better?',description:'Start with a specific person and a recurring problem. A service, local business, or small software tool can be a useful first idea.',actions:['Write down three problems you’ve seen people face.','Choose one audience you can actually speak with.','Describe how they solve the problem today and what makes it difficult.'],outcome:'A one-sentence problem statement: “For [person], [problem] makes it hard to [goal].”',resourceIds:['problems','learn-build'],communityIds:['startup-school']},
 {name:'Validate the need',short:'Validate',question:'Is the problem real enough to act on?',description:'Talk to potential customers before investing heavily in a solution. Look for examples of what they do, not only what they say they might like.',actions:['Ask a few potential customers about the last time they faced this problem.','Record their current workaround and what it costs them in time or effort.','Write down what evidence would make you continue, change direction, or stop.'],outcome:'A short set of customer notes and one assumption worth testing next.',resourceIds:['business-plan','learn-build'],communityIds:['score','startup-school']},
 {name:'Shape a first offer',short:'Plan',question:'What is the smallest useful promise?',description:'Decide what you will deliver, who it is for, and how you will test whether the offer is useful.',actions:['Define one result your first customer should get.','Compare existing alternatives and write down how your approach helps.','Sketch the main costs, a possible price, and what you need to learn about willingness to pay.'],outcome:'A one-page offer with its audience, result, scope, and main assumptions.',resourceIds:['business-plan','startup-india-guide'],communityIds:['score','tie','yc-matching']},
 {name:'Build a small version',short:'Build',question:'Can one person use it end to end?',description:'Build only enough to test the core promise. For a service, this could be a manual pilot; for a product, it could be one working flow.',actions:['Choose the single customer journey that matters most.','Build or deliver it with the simplest tools you can maintain.','Test it with a few people and fix what prevents them reaching the result.'],outcome:'A usable pilot or prototype with a clear way to collect feedback.',resourceIds:['learn-build'],communityIds:['yc-matching','techstars','startup-school']},
 {name:'Launch & find customers',short:'Launch',question:'Where will your first customers find you?',description:'Make the offer clear and share it where your intended customers already look for help. Check local requirements before taking the business live.',actions:['Create a clear page or short description of the offer and how to try it.','Choose one relevant channel and invite a small initial group to try it.','Check the official business, tax, and licensing guidance for your location and activity.'],outcome:'A small launch, a way to contact you, and a plan for handling feedback.',resourceIds:['launch-guide','marketing','business-plan'],communityIds:['product-hunt','startup-grind','score']},
 {name:'Learn & improve',short:'Improve',question:'What makes people come back?',description:'Use real feedback and repeat usage to choose what to improve next. Progress may mean refining the idea or deciding to change course.',actions:['Ask what worked, what was confusing, and what people did next.','Track a small useful signal, such as completed trials or repeat customers.','Pick one improvement, test it, and compare what changed.'],outcome:'A weekly learning note and one concrete improvement to try.',resourceIds:['marketing','learn-build'],communityIds:['startup-school','tie','score']}
] as const;
