'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,Compass,Globe2,Lightbulb,MapPin,Search,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {COMMUNITIES,GUIDES,JOURNEY,type CommunityResource,type Guide} from '@/lib/community';
function Filter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="hub-field">{label}<Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>;}
function CommunityCard({item}:{item:CommunityResource}){return <article className="hub-card hub-community"><div className="hub-card-top"><span className={`hub-mark hub-mark-${item.initials.toLowerCase().replace(/[^a-z]/g,'')}`} aria-hidden="true">{item.initials}</span><span className="hub-tag">{item.focus}</span></div><p className="hub-organization">{item.organization}</p><h3>{item.name}</h3><p className="hub-description">{item.description}</p><div className="hub-community-details"><span><MapPin size={14}/>{item.region}</span><span><Globe2 size={14}/>{item.format}</span></div><p className="hub-access">{item.access}</p><p className="hub-note">{item.note}</p><a className="hub-visit" href={item.url} target="_blank" rel="noopener noreferrer" aria-label={`Explore ${item.name} on ${item.organization}'s website`}><span>Explore community</span><ArrowUpRight size={19}/></a></article>;}
function GuideCard({item}:{item:Guide}){return <article className="hub-card hub-guide"><div className="hub-card-top"><BookOpen size={21}/><span className="hub-tag">{item.stage}</span></div><p className="hub-organization">{item.organization}</p><h3>{item.title}</h3><p className="hub-description">{item.description}</p><p className="hub-note">{item.note}</p><a className="hub-visit" href={item.url} target="_blank" rel="noopener noreferrer" aria-label={`Read ${item.title} from ${item.organization}`}><span>Read the guide</span><ArrowUpRight size={19}/></a></article>;}
export default function Community(){
 const [tab,setTab]=useState('communities'),[region,setRegion]=useState('All regions'),[focus,setFocus]=useState('Any purpose'),[search,setSearch]=useState(''),[step,setStep]=useState(0);
 const [guideSearch,setGuideSearch]=useState('');
 const matches=useMemo(()=>COMMUNITIES.filter(item=>(region==='All regions'||item.region===region||item.region==='Worldwide')&&(focus==='Any purpose'||item.focus===focus)&&`${item.name} ${item.organization} ${item.description}`.toLowerCase().includes(search.trim().toLowerCase())),[region,focus,search]);
 const guides=GUIDES.filter(item=>`${item.title} ${item.description} ${item.organization}`.toLowerCase().includes(guideSearch.trim().toLowerCase()));
 const current=JOURNEY[step];
 return <main className="hub-main">
  <div className="hub-heading"><div><p className="hub-eyebrow">COMMUNITIES & STARTUP RESOURCES</p><h1>Find your people.<br/><span>Bring an idea to life.</span></h1><p>Established communities to join. Practical guidance to move from<br className="hub-desktop-break"/> “what if” to your first customer — wherever you’re starting.</p></div><div className="hub-intro-card"><span><Compass size={23}/></span><div><p>HAVE AN IDEA IN MIND?</p><h2>Make your next step clear.</h2><button onClick={()=>setTab('journey')}>Explore the idea-to-launch path <ArrowRight size={17}/></button></div></div></div>
  <Tabs value={tab} onValueChange={setTab} className="hub-tabs"><TabsList className="hub-tab-list" aria-label="Startup resource sections"><TabsTrigger value="communities"><Users size={17}/>Find communities</TabsTrigger><TabsTrigger value="journey"><Lightbulb size={17}/>Idea to launch</TabsTrigger><TabsTrigger value="guides"><BookOpen size={17}/>Practical guides</TabsTrigger></TabsList>
   <TabsContent value="communities"><section aria-labelledby="hub-directory-title"><div className="hub-section-heading"><div><h2 id="hub-directory-title">A good place to belong.</h2><p>Explore groups that already exist. Join, register, or contact them on their own websites.</p></div><span className="hub-count">{matches.length} {matches.length===1?'place':'places'} to explore</span></div><div className="hub-filters"><label className="hub-field hub-search">Search communities<div><Search size={17}/><Input value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} placeholder="A community, skill, or interest"/></div></label><Filter label="Where are you looking?" value={region} options={['All regions','India','United States','Worldwide']} onChange={setRegion}/><Filter label="What do you need?" value={focus} options={['Any purpose','Co-founders','Mentoring','Events','Learning','Launch & feedback']} onChange={setFocus}/></div><p className="hub-location-note"><MapPin size={15}/>{region==='All regions'?'Looking for something near you? Use each organization’s location, chapter, or event search.':'Worldwide options are included. Use the original site to check availability in your city.'}</p>
    {matches.length?<div className="hub-card-grid">{matches.map(item=><CommunityCard key={item.id} item={item}/>)}</div>:<div className="hub-card hub-empty"><Search size={29}/><h3>No matches in this collection.</h3><p>Try another keyword or broaden your filters.</p><Button variant="outline" onClick={()=>{setSearch('');setFocus('Any purpose');setRegion('All regions');}}>Clear filters</Button></div>}
    <div className="hub-bottom-invite"><div><p className="hub-eyebrow">YOU DON’T NEED THE WHOLE PLAN YET</p><h2>Start with one useful conversation.</h2><p>Find a group that fits your stage, learn what others are working on, and ask one specific question.</p></div><Button onClick={()=>setTab('journey')}>Find your next step <ArrowRight size={17}/></Button></div>
   </section></TabsContent>
   <TabsContent value="journey"><div className="hub-section-heading"><div><h2>From a first thought to a real offering.</h2><p>A flexible path for a product, local business, or service. Choose the stage you’re at.</p></div></div><div className="hub-journey"><nav className="hub-steps" aria-label="Idea-to-launch stages">{JOURNEY.map((item,index)=><button key={item.name} onClick={()=>setStep(index)} aria-current={step===index?'step':undefined}><span>{String(index+1).padStart(2,'0')}</span><div><small>STEP {index+1}</small><strong>{item.name}</strong></div><ArrowRight size={16}/></button>)}</nav><section className="hub-card hub-stage" aria-live="polite" aria-atomic="true"><p className="hub-eyebrow">STEP {step+1} OF {JOURNEY.length} · {current.short.toUpperCase()}</p><h3>{current.question}</h3><p className="hub-stage-description">{current.description}</p><h4>Try these next</h4><ol className="hub-actions">{current.actions.map((action,index)=><li key={action}><span>{index+1}</span><p>{action}</p></li>)}</ol><div className="hub-outcome"><Check size={20}/><div><h4>What you’ll have</h4><p>{current.outcome}</p></div></div><div className="hub-stage-links"><h4>Go a little deeper</h4>{GUIDES.filter(g=>(current.resourceIds as readonly string[]).includes(g.id)).map(g=><a key={g.id} href={g.url} target="_blank" rel="noopener noreferrer"><span>{g.title}<small>{g.organization}</small></span><ArrowUpRight size={18}/></a>)}</div><div className="hub-stage-footer"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(v=>v-1)}>Previous step</Button>{step<JOURNEY.length-1?<Button onClick={()=>setStep(v=>v+1)}>Next: {JOURNEY[step+1].short} <ArrowRight size={16}/></Button>:<Button onClick={()=>setTab('communities')}>Find a community <Users size={16}/></Button>}</div></section></div><div className="hub-related"><h2>People to learn with at this stage</h2><div className="hub-related-links">{COMMUNITIES.filter(c=>(current.communityIds as readonly string[]).includes(c.id)).map(c=><a key={c.id} href={c.url} target="_blank" rel="noopener noreferrer"><span>{c.name}<small>{c.access}</small></span><ArrowUpRight size={20}/></a>)}</div></div></TabsContent>
   <TabsContent value="guides"><div className="hub-section-heading"><div><h2>A little guidance goes a long way.</h2><p>Read the original advice, put one part into practice, and come back when you need the next step.</p></div></div><label className="hub-field hub-guide-search">Search guides<Input value={guideSearch} onChange={e=>setGuideSearch(e.target.value)} placeholder="Market research, launch, customers…" maxLength={100}/></label><div className="hub-card-grid">{guides.map(item=><GuideCard key={item.id} item={item}/>)}</div>{!guides.length&&<div className="hub-card hub-empty"><h3>No guides match that search.</h3><Button variant="outline" onClick={()=>setGuideSearch('')}>Clear search</Button></div>}</TabsContent>
  </Tabs>
  <footer className="hub-footer"><Globe2 size={19}/><p>Links go to independent organizations. We don’t import their members or verify who is nearby or free to meet. Check the original website for current locations, eligibility, dates, and prices. Sources reviewed September 14, 2026.</p></footer>
 </main>;
}
