'use client';
import {Progress} from '@/components/ui/progress';
import {amount,type NutritionSummary} from '@/lib/nutrients';
const cards=[
 ['1003','Protein','g',50,'Muscle maintenance and tissue repair'],['1079','Fiber','g',28,'Digestive health and bowel regularity'],['1090','Magnesium','mg',420,'Normal muscle and nerve function'],['1095','Zinc','mg',11,'Protein synthesis and wound healing'],['1089','Iron','mg',18,'Oxygen transport in the blood'],['1087','Calcium','mg',1300,'Bones, teeth and muscle contraction'],['1114','Vitamin D','µg',20,'Calcium absorption and bone health'],['1178','Vitamin B12','µg',2.4,'Nerve function and red blood cells'],['1190','Folate','µg DFE',400,'Cell division and DNA synthesis'],['1162','Vitamin C','mg',90,'Collagen formation and iron absorption'],['1092','Potassium','mg',4700,'Normal muscle and nerve function'],['1176','Biotin','µg',30,'Normal nutrient metabolism'],
] as const;
export default function DailyNutrients({summary,references,custom}:{summary:NutritionSummary;references?:Record<string,number>;custom:{protein:number;fiber:number;magnesium:number}}){
 const existing:Record<string,number>={'1003':custom.protein,'1079':custom.fiber,'1090':custom.magnesium};
 return <section><h2>Daily nutrient overview</h2><p className="muted-copy">Known intake for the selected day. Each card labels its reference: your profile, your saved goal, or a general FDA Daily Value. Percentages describe logged food, not absorption or a diagnosis.</p><div className="nutrient-cards nutrient-expanded">{cards.map(([id,name,unit,dv,role],i)=>{const n=summary.nutrients[id];const goal=references?.[id]??existing[id]??dv;const basis=references?.[id]!=null?'Profile reference':existing[id]!=null?'Saved goal':'General Daily Value';const percentage=n?.value==null?null:n.value/goal*100;return <article className={`nutrient-card nutrient-${i%3}`} key={id}><div className="nutrient-label"><h3>{name}</h3><span>{percentage===null?'Unknown':`${Math.round(percentage)}%`}</span></div><p className="nutrient-number">{n?.value==null?'—':amount(n.value)}<span>{unit}</span></p><Progress aria-label={`${name} compared with ${basis.toLowerCase()}`} value={percentage===null?0:Math.min(100,percentage)}/><p className="nutrient-card-bottom">{amount(goal,unit)} · {basis}</p><p className="nutrient-role">{role}</p><small>{n?.covered??0}/{summary.items} foods have values · {n?.value==null?'No known intake':(n?.covered??0)<summary.items?'Partial subtotal':'Food estimate'}</small></article>})}</div><p className="estimate-note">100% is a reference, not a limit or a reason to take supplements. More is not always better. Missing foods and portions can understate intake; one low day does not establish deficiency.</p><details className="fit-evidence"><summary>Hair, muscle and nutrient references</summary><p>Adequate nutrition supports normal body function. These cards do not promise hair growth or muscle gain. Biotin supplements have little supporting evidence for hair growth in people without a deficiency; persistent hair loss needs individual assessment.</p><a href="https://ods.od.nih.gov/factsheets/Biotin-Consumer/" target="_blank" rel="noopener noreferrer">NIH · biotin and hair claims</a> · <a href="https://ods.od.nih.gov/factsheets/Zinc-HealthProfessional/" target="_blank" rel="noopener noreferrer">NIH · zinc</a> · <a href="https://www.fda.gov/food/nutrition-facts-label/daily-value-nutrition-and-supplement-facts-labels" target="_blank" rel="noopener noreferrer">FDA · Daily Values</a></details></section>;
}
