'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
export default function MealPhoto(){
 const [photo,setPhoto]=useState<string|null>(null),[error,setError]=useState('');const camera=useRef<HTMLInputElement>(null),upload=useRef<HTMLInputElement>(null);const request=useRef(0);
 useEffect(()=>()=>{request.current++;},[]);
 useEffect(()=>()=>{if(photo)URL.revokeObjectURL(photo);},[photo]);
 function choose(file?:File){if(!file)return;const id=++request.current;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG or WebP photo. Convert HEIC photos to JPG first.');return;}if(file.size>15*1024*1024){setError('This photo is too large. Choose a photo smaller than 15 MB.');return;}const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{if(id!==request.current){URL.revokeObjectURL(url);return;}setPhoto(url);};img.onerror=()=>{URL.revokeObjectURL(url);if(id===request.current)setError('This image could not be opened. Try a different photo.');};img.src=url;}
 return <section className="meal-photo"><h3>Use a meal photo as your reference</h3><p>Keep your plate in view while you select foods and confirm portions below. This free version does not identify foods or measure portions automatically.</p><input ref={camera} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{choose(e.target.files?.[0]);e.target.value='';}}/><input ref={upload} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.target.value='';}}/><div className="fit-tool-buttons"><Button type="button" variant="outline" onClick={()=>camera.current?.click()}>Take a photo</Button><Button type="button" variant="outline" onClick={()=>upload.current?.click()}>Choose photo</Button>{photo&&<Button type="button" variant="ghost" onClick={()=>{request.current++;setPhoto(null);setError('');}}>Remove photo</Button>}</div>{photo&&<img src={photo} alt="Your meal reference, selected on this device"/>}{error&&<p role="alert">{error}</p>}<p className="fit-small">Photo stays on this device and is discarded when you close the meal editor. Only the foods, portions and notes you save go to your private log. Camera availability depends on your browser; JPG, PNG and WebP up to 15 MB.</p>{photo&&<ol><li>Choose breakfast, lunch, dinner or snack.</li><li>Match each ingredient and its preparation. Include oils, sauces and drinks.</li><li>Enter weighed portions or mark estimates/unknowns, then save the meal.</li></ol>}</section>;
}
