'use client';
import {useEffect,useState} from 'react';
import type {FitnessResult} from '@/lib/fitness-plan';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
function Evidence({children,url,label}:{children:React.ReactNode;url:string;label:string}){return <details className="fit-evidence"><summary>Why this helps</summary><p>{children}</p><a href={url} target="_blank" rel="noopener noreferrer">{label} ↗</a></details>}
export default function PracticalTools({mode,data}:{mode:string;data:FitnessResult|null}){
 const [moderate,setModerate]=useState(0),[vigorous,setVigorous]=useState(0),[strength,setStrength]=useState(0),[meals,setMeals]=useState(3),[effort,setEffort]=useState('steady');
 const [seconds,setSeconds]=useState(90),[end,setEnd]=useState<number|null>(null);
 useEffect(()=>{if(end===null)return;const tick=()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setSeconds(left);if(left===0)setEnd(null);};tick();const id=setInterval(tick,250);return()=>clearInterval(id);},[end]);
 const equivalent=moderate+vigorous*2;const target=data?.targets;const held=data?.workout?.held;
 return <section className="fit-surface fit-tools"><p className="fit-kicker">SMALL TOOLS, USEFUL NEXT STEPS</p><h2>{mode==='workouts'?'Make your training easier to follow':'Make your nutrition easier to understand'}</h2><p className="fit-small">These interactive worksheets reset when you leave this page. They do not add entries to your journal.</p><div className="fit-tools-grid">{mode==='workouts'?<>
 <article className="fit-inset"><h3>Your weekly movement</h3><p>Enter this week’s activity to compare with general adult guidance.</p><label>Moderate aerobic minutes<Input type="number" min={0} max={3000} value={moderate} onChange={e=>setModerate(Math.max(0,Math.min(3000,Number(e.target.value)||0)))}/></label><label>Vigorous aerobic minutes<Input type="number" min={0} max={1500} value={vigorous} onChange={e=>setVigorous(Math.max(0,Math.min(1500,Number(e.target.value)||0)))}/></label><label>Strength days<Input type="number" min={0} max={7} value={strength} onChange={e=>setStrength(Math.max(0,Math.min(7,Math.floor(Number(e.target.value)||0))))}/></label><p><strong>{equivalent} / 150</strong> moderate-equivalent minutes · <strong>{strength} / 2</strong> strength days</p><progress max={150} value={Math.min(150,equivalent)} aria-label="Weekly aerobic reference progress"/><p>{equivalent<150?`${150-equivalent} minutes below the starting reference. Build gradually; some movement is worthwhile.`:'You meet the starting aerobic reference. Recovery still matters.'}</p><p className="fit-small">Count aerobic and strength activity separately; don’t count the same aerobic minutes twice. This is a reference, not a prescribed target for a medical condition.</p><Evidence url="https://www.who.int/initiatives/behealthy/physical-activity" label="WHO adult activity guidance">Adult guidance combines 150–300 moderate minutes (or 75–150 vigorous minutes) weekly with strength work on at least two days. One vigorous minute counts as two moderate minutes here.</Evidence></article>
 <article className="fit-inset"><h3>Rest between sets</h3><p>Choose a starting break; take longer if you need to recover.</p><div className="fit-tool-buttons">{[60,90,120].map(n=><Button key={n} variant="outline" onClick={()=>{setEnd(null);setSeconds(n);}}>{n} sec</Button>)}</div><output className="fit-timer" aria-label="Seconds remaining">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</output><div className="fit-tool-buttons"><Button onClick={()=>end===null?setEnd(Date.now()+(seconds||90)*1000):setEnd(null)}>{end===null?'Start / resume':'Pause'}</Button><Button variant="outline" onClick={()=>{setEnd(null);setSeconds(90);}}>Reset</Button></div><p role="status">{seconds===0?'Rest timer finished. Start only when you feel ready.':'The timer is a convenience, not a recovery measurement.'}</p><h3>How did the set feel?</h3><label>Effort<select value={effort} onChange={e=>setEffort(e.target.value)}><option value="steady">Controlled, a few reps left</option><option value="easy">Very easy</option><option value="hard">Form broke down / exhausted</option><option value="pain">Pain or unusual symptoms</option></select></label><p>{effort==='pain'?'Stop the exercise. Get appropriate medical guidance for pain or unusual symptoms.':held?'Your profile or check-in has paused automatic progression. Follow your individual guidance.':effort==='easy'?'Record the reps and load in your workout notes. Review repeated easy sessions before changing your plan.':effort==='hard'?'Rest longer or reduce the load. Keep the next set controlled rather than chasing exhaustion.':'Keep practicing controlled repetitions. You do not need to reach failure on every set.'}</p><Evidence url="https://pubmed.ncbi.nlm.nih.gov/38970765/" label="Robinson et al., 2024 · meta-regressions">Research distinguishes strength from muscle growth when examining closeness to failure. It does not establish one ideal effort for everyone; this check offers conservative technique and recovery prompts, not an automatic load prescription.</Evidence></article>
 </>:<><article className="fit-inset"><h3>Spread your protein across meals</h3>{target?<><label>Meals or eating occasions<select value={meals} onChange={e=>setMeals(Number(e.target.value))}>{[2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label><p className="fit-protein-number">≈ {Math.round(target.protein/meals)} g <small>per occasion</small></p><p>Your existing {target.protein} g daily plan divided across {meals} occasions. This is a planning aid, not a requirement to eat identical meals.</p></>:<p>Complete an eligible profile to split your existing daily protein estimate. No new target is calculated without it.</p>}<Evidence url="https://pubmed.ncbi.nlm.nih.gov/28698222/" label="Morton et al., 2018 · systematic review">Across resistance-training trials in healthy adults, average additional lean-mass benefit plateaued around 1.6 g/kg/day total protein. This is not an individual threshold or evidence that everyone needs supplements. The equal meal split above is a convenience, not a result tested by that review.</Evidence></article>
 <article className="fit-inset"><h3>Know what your log can tell you</h3>{data&&data.summary.items>0?<><p><strong>{data.summary.items}</strong> foods logged today · <strong>{data.summary.unknownPortions}</strong> with unknown portions</p>{[['1003','Protein'],['1079','Fiber'],['1090','Magnesium']].map(([id,name])=>{const n=data.summary.nutrients[id];return <p key={id}><strong>{name}:</strong> {n?.covered??0}/{data.summary.items} foods have values. {(n?.covered??0)<data.summary.items?'Coverage is incomplete; a low total cannot establish a deficiency.':'All listed foods have values; portion estimates and unlogged food still matter.'}</p>})}</>:<p>No food entries available for today. Log foods and portions in “What did you eat?” to see nutrient coverage here.</p>}<h3>Build fiber variety</h3><p>Include foods such as beans or lentils, whole grains, vegetables, fruit, nuts and seeds as your preferences and allergies allow. Increase fiber gradually; follow individual advice for digestive conditions.</p><Evidence url="https://pubmed.ncbi.nlm.nih.gov/30638909/" label="Reynolds et al., 2019 · systematic reviews">Higher fiber and whole-grain intake was associated with better long-term health outcomes, with benefits observed around 25–29 g fiber per day. This population evidence complements, rather than replaces, the age-based reference in your profile.</Evidence></article></>}</div></section>;
}
