'use client';

import {useCallback,useEffect,useRef,useState} from 'react';
import {useDeviceToday} from '@/app/device-time';
import {dayAfterClockChange} from '@/lib/device-time';
import {Utensils,Dumbbell,Plus,Settings2,Pencil,Trash2,Footprints,Flame,ShieldCheck,Info,ChevronLeft,ChevronRight,Check,Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {MAIN,VITAMINS,AMINO_ACIDS,OTHER,amount,type NutritionSummary,type Suggestions,type NutrientSpec} from '@/lib/nutrients';
import {daysBefore,DEFAULT_SETTINGS,type Food,type MealItem,type MealData,type WorkoutData,type LogEntry,type WellnessSettings,type WellnessState} from '@/lib/wellness-types';

type Payload=WellnessState&{summary:NutritionSummary;suggestions:Suggestions;history:{day:string;summary:NutritionSummary}[]};
type Mutation={action:'save-entry';entry:{id:string;day:string;data:MealData|WorkoutData}}|{action:'delete-entry';id:string}|{action:'save-settings';settings:WellnessSettings}|{action:'complete-day';day:string;complete:boolean};
const ALLERGENS=['Milk','Eggs','Fish','Shellfish','Tree nuts','Peanuts','Wheat','Soy','Sesame'];
function prettyDay(day:string){return new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});}
function Choice({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(value:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
const opts=(values:string[])=>values.map(value=>({value,label:value}));

export default function Wellness({onChanged}:{onChanged?:()=>Promise<void>}){
 const today=useDeviceToday();
 return today?<WellnessForDevice today={today} onChanged={onChanged}/>:<main className="wellness-main"><p role="status">Loading your local day…</p></main>;
}

function WellnessForDevice({today,onChanged}:{today:string;onChanged?:()=>Promise<void>}){
 const [day,setDay]=useState(today);const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState('');const [authError,setAuthError]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const [modal,setModal]=useState<'meal'|'workout'|'goals'|null>(null);const [editing,setEditing]=useState<LogEntry|null>(null);const [deleting,setDeleting]=useState<LogEntry|null>(null);const [formError,setFormError]=useState('');
 const previousToday=useRef(today);
 useEffect(()=>{
  if(previousToday.current===today||modal||saving)return;
  const previous=previousToday.current;
  previousToday.current=today;
  setDay(selected=>dayAfterClockChange(selected,previous,today));
 },[today,modal,saving]);
 const loadId=useRef(0);const dayRef=useRef(day);dayRef.current=day;
 const reload=useCallback(async()=>{const id=++loadId.current;const target=dayRef.current;setLoading(true);setError('');try{const r=await fetch(`/api/wellness?from=${daysBefore(target,6)}&to=${target}`,{cache:'no-store'});const next=await r.json() as Payload & {error?:string};if(!r.ok){if(r.status===401)setAuthError(true);throw new Error(next.error||'Could not load your logs.');}if(id===loadId.current){setData(next);setAuthError(false);}}catch(e){if(id===loadId.current)setError(e instanceof Error?e.message:'Could not load your logs.');}finally{if(id===loadId.current)setLoading(false);}},[]);
 useEffect(()=>{setData(null);void reload();},[day,reload]);
 async function mutate(body:Mutation){setSaving(true);setFormError('');try{const r=await fetch('/api/wellness',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json() as {error?:string};if(!r.ok){if(r.status===401)setAuthError(true);throw new Error(result.error||'Could not save. Please try again.');}await reload();await onChanged?.();toast.success(body.action==='delete-entry'?'Entry removed':'Saved to your private log');return true;}catch(e){const message=e instanceof Error?e.message:'Could not save. Please try again.';setFormError(message);toast.error(message);return false;}finally{setSaving(false);}}
 function open(kind:'meal'|'workout'|'goals',entry:LogEntry|null=null){setEditing(entry);setFormError('');setModal(kind);}
 async function saveEntry(value:MealData|WorkoutData){if(await mutate({action:'save-entry',entry:{id:editing?.id??crypto.randomUUID(),day:editing?.day??day,data:value}}))setModal(null);}
 const entries=data?.entries.filter(e=>e.day===day)??[];const workouts=entries.filter(e=>e.data.type==='workout').map(e=>e.data as WorkoutData);
 const sumField=(key:'minutes'|'steps'|'calories')=>workouts.some(w=>w[key]!==null)?workouts.reduce((n,w)=>n+(w[key]??0),0):null;
 const summary=data?.summary;const targets=data?[data.settings.targets.protein,data.settings.targets.fiber,data.settings.targets.magnesium]:[50,28,420];
 return <main className="wellness-main"><Toaster position="bottom-center"/>
  <div className="wellness-heading"><div><p className="eyebrow">YOUR PRIVATE DAILY LOG</p><h1>Fitness & Nutrition<span>.</span></h1><p>Make room for what makes you feel well.</p></div><Button variant="outline" onClick={()=>open('goals')} disabled={!data||loading}><Settings2 size={16}/> Goals & preferences</Button></div>
  <div className="wellness-toolbar"><div className="date-control"><Button variant="ghost" size="icon" aria-label="Previous day" onClick={()=>setDay(daysBefore(day,1))} disabled={saving}><ChevronLeft/></Button><label><span className="sr-only">Log date</span><Input type="date" value={day} min="1900-01-01" max={today} disabled={saving} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)&&e.target.value<=today)setDay(e.target.value);}}/></label><Button variant="ghost" size="icon" aria-label="Next day" disabled={day>=today||saving} onClick={()=>setDay(daysBefore(day,-1))}><ChevronRight/></Button>{day!==today&&<Button variant="link" onClick={()=>setDay(today)}>Today</Button>}</div><div className="toolbar-actions"><Button variant="outline" onClick={()=>open('workout')} disabled={!data||loading}><Dumbbell size={16}/>Log activity</Button><Button onClick={()=>open('meal')} disabled={!data||loading}><Plus size={17}/>Add meal</Button></div></div>
  {error&&<div className="wellness-error" role="alert"><p>{error}</p>{authError?<a href="/signin-with-chatgpt?return_to=%2Fwellness" target="_top">Sign in again</a>:<Button variant="outline" onClick={()=>void reload()}>Try again</Button>}</div>}
  {loading&&<div className="nutrient-cards" aria-label="Loading your logs">{MAIN.map(n=><Skeleton key={n.id} className="h-40 rounded-xl"/>)}</div>}
  {!loading&&data&&summary&&<>
   <div className="nutrient-cards">{MAIN.map((spec,i)=>{const total=summary.nutrients[spec.id];return <section className={`nutrient-card nutrient-${i}`} key={spec.id}><div className="nutrient-label"><h2>{spec.name}</h2><span>{total.covered<total.total?'Partial estimate':'Food estimate'}</span></div><p className="nutrient-number">{total.value===null?'—':amount(total.value)}<span>{spec.unit}</span></p><Progress aria-label={`${spec.name} compared with your goal`} value={total.value===null?0:Math.min(100,total.value/targets[i]*100)}/><div className="nutrient-card-bottom"><span>{targets[i]} {spec.unit} goal</span><span>{summary.items?`${total.covered}/${total.total} foods counted`:'No food logged'}</span></div></section>;})}</div>
   <p className="estimate-note"><Info size={16}/>{summary.items?`${summary.estimatedPortions} estimated portion${summary.estimatedPortions===1?'':'s'} · ${summary.unknownPortions} unknown portion${summary.unknownPortions===1?'':'s'} · ${summary.unlistedFoods} unlisted food${summary.unlistedFoods===1?'':'s'}. `:''}Missing nutrients are unknown, not zero. Even measured portions use food composition estimates.</p>
   <div className="wellness-columns"><div className="daily-column">
    <section className="wellness-panel daily-log"><div className="panel-heading"><div><p className="eyebrow">{day===today?'TODAY':prettyDay(day)}</p><h2>Your meals</h2></div><Utensils size={21}/></div>
     {entries.filter(e=>e.data.type==='meal').length===0?<div className="log-empty"><Utensils/><h3>A little detail goes a long way.</h3><p>Add what you ate and the portion you remember. It’s okay if you’re unsure.</p><Button variant="outline" onClick={()=>open('meal')}><Plus size={16}/>Log your first meal</Button></div>:entries.filter(e=>e.data.type==='meal').map(entry=><EntryCard key={entry.id} entry={entry} edit={()=>open('meal',entry)} remove={()=>{setFormError('');setDeleting(entry);}}/>)}
     <label className="complete-check"><Checkbox checked={data.completeDays.includes(day)} disabled={saving||summary.mealCount===0} onCheckedChange={checked=>void mutate({action:'complete-day',day,complete:checked===true})}/><span>All meals for this day are logged<small>Still an estimate, even when your log is complete.</small></span></label>
    </section>
    <section className="wellness-panel"><div className="panel-heading"><div><p className="eyebrow">MANUAL ACTIVITY LOG</p><h2>Your movement</h2></div><Dumbbell size={21}/></div><div className="movement-totals"><div><Dumbbell/><strong>{amount(sumField('minutes'))}</strong><span>minutes logged</span></div><div><Footprints/><strong>{amount(sumField('steps'))}</strong><span>steps logged</span></div><div><Flame/><strong>{amount(sumField('calories'))}</strong><span>kcal reported</span></div></div><p className="muted-copy">Totals use the values you enter. Calories are estimates; device syncing is not connected.</p>{entries.filter(e=>e.data.type==='workout').map(entry=><EntryCard key={entry.id} entry={entry} edit={()=>open('workout',entry)} remove={()=>{setFormError('');setDeleting(entry);}}/>)}{!workouts.length&&<Button variant="outline" className="full-width" onClick={()=>open('workout')}><Plus size={16}/>Add minutes, steps or a workout</Button>}</section>
   </div><aside className="suggestions-panel"><div className="panel-heading"><div><p className="eyebrow">A LITTLE HELP WITH THE NEXT MEAL</p><h2>On your plate next</h2></div></div><p className="muted-copy">{data.suggestions.basis}</p>{data.suggestions.meals.length?data.suggestions.meals.map((meal,i)=><article className="meal-suggestion" key={meal.name}><span className="suggestion-number">0{i+1}</span><div><h3>{meal.name}</h3><p className="suggestion-focus">{meal.focus}</p><ul>{meal.ingredients.map(ingredient=><li key={ingredient}>{ingredient}</li>)}</ul><p className="suggestion-nutrients">≈ {Math.round(meal.protein)} g protein <span>·</span> {Math.round(meal.fiber)} g fiber <span>·</span> {Math.round(meal.magnesium)} mg magnesium</p><p className="allergen-note">{meal.allergens.length?`Contains: ${meal.allergens.join(', ')}`:'No selected major allergens in these ingredients'}</p></div></article>):<p>No combinations match these exclusions. Adjust your preferences or log your own foods.</p>}<p className="muted-copy suggestion-disclaimer">Estimates cover only the listed ingredients and portions. Check ingredients and labels for your dietary needs, including cross-contact; oats may need gluten-free certification. Suggestions describe logged intake, not a diagnosis of nutrient deficiency.</p></aside></div>
   <section className="wellness-panel nutrient-details"><div className="panel-heading"><div><p className="eyebrow">LOOK A LITTLE CLOSER</p><h2>The nutrient details</h2></div><span className="muted-copy">{prettyDay(day)}</span></div><p className="muted-copy">Known amounts are subtotals for foods with both a portion and nutrient data. They may be lower than what you actually consumed.</p><Tabs defaultValue="vitamins"><TabsList className="detail-tabs"><TabsTrigger value="vitamins">Vitamins</TabsTrigger><TabsTrigger value="amino">Amino acids</TabsTrigger><TabsTrigger value="other">Other nutrients</TabsTrigger></TabsList><TabsContent value="vitamins"><NutrientTable specs={VITAMINS} summary={summary}/><p className="muted-copy">References are general FDA label Daily Values for adults and children 4+, not individualized targets. K1 excludes K2; niacin excludes tryptophan-derived equivalents.</p></TabsContent><TabsContent value="amino"><NutrientTable specs={AMINO_ACIDS} summary={summary}/><p className="muted-copy">No Daily Values are established for individual amino acids. Cysteine, asparagine and glutamine are unreported in this catalog; they are not inferred from related compounds or protein.</p></TabsContent><TabsContent value="other"><NutrientTable specs={OTHER} summary={summary}/></TabsContent></Tabs></section>
   <section className="wellness-panel recent-review"><div className="panel-heading"><div><p className="eyebrow">THE LAST 7 DAYS</p><h2>Your recent food logs</h2></div><span className="muted-copy">{data.suggestions.loggedDays} days with food · {data.suggestions.completeDays} marked complete</span></div><div className="week-strip">{Array.from({length:7},(_,i)=>daysBefore(day,6-i)).map(d=>{const found=data.history.find(h=>h.day===d);return <button key={d} onClick={()=>setDay(d)} className={d===day?'selected':''}><span>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{new Date(d+'T12:00:00').getDate()}</strong><small>{found?.summary.mealCount?`${found.summary.mealCount} meals`:'No food log'}</small>{data.completeDays.includes(d)&&<Check size={15} aria-label="Marked complete"/>}</button>;})}</div><p className="muted-copy">Choose a day to review its entries. No food log means unknown intake. Suggestions compare only days with food entries, and incomplete portions reduce coverage.</p></section>
  </>}
  <footer className="wellness-footer"><ShieldCheck size={18}/><p>Private to your signed-in account. Nutrition data: <a href="https://fdc.nal.usda.gov/download-datasets/" target="_blank" rel="noreferrer">USDA FoodData Central</a>, SR Legacy (2018) and Foundation Foods (April 2026). <a href="https://www.fda.gov/food/nutrition-facts-label/daily-value-nutrition-and-supplement-facts-labels" target="_blank" rel="noreferrer">About Daily Values</a>. No AI calls are used.</p></footer>
  <Dialog open={modal!==null} onOpenChange={v=>{if(!v&&!saving)setModal(null);}}><DialogContent className="wellness-dialog"><DialogHeader><DialogTitle>{modal==='goals'?'Goals & food preferences':`${editing?'Edit':'Log'} ${modal==='meal'?'a meal':'an activity'}`}</DialogTitle><DialogDescription>{modal==='goals'?'Choose useful references for your food logs.':`${prettyDay(editing?.day??day)} · Private to your account`}</DialogDescription></DialogHeader>{modal==='meal'&&<MealEditor key={editing?.id??'new'} initial={editing?.data.type==='meal'?editing.data:undefined} onSave={saveEntry} saving={saving}/>} {modal==='workout'&&<WorkoutEditor key={editing?.id??'new'} initial={editing?.data.type==='workout'?editing.data:undefined} onSave={saveEntry} saving={saving}/>} {modal==='goals'&&<GoalsEditor initial={data?.settings??DEFAULT_SETTINGS} onSave={async settings=>{if(await mutate({action:'save-settings',settings}))setModal(null);}} saving={saving}/>} {formError&&<p className="form-error" role="alert">{formError}{authError&&<> <a href="/signin-with-chatgpt?return_to=%2Fwellness" target="_top">Sign in again</a></>}</p>}</DialogContent></Dialog>
  <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!saving)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this entry?</AlertDialogTitle><AlertDialogDescription>This removes it from your private log and recalculates the day’s totals.</AlertDialogDescription></AlertDialogHeader>{formError&&<p className="form-error" role="alert">{formError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={saving}>Keep entry</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={async e=>{e.preventDefault();if(deleting&&await mutate({action:'delete-entry',id:deleting.id}))setDeleting(null);}}>Remove entry</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}

function EntryCard({entry,edit,remove}:{entry:LogEntry;edit:()=>void;remove:()=>void}){const d=entry.data;return <article className="log-entry"><div className="entry-title"><h3>{d.type==='meal'?d.meal:d.activity}</h3><div><Button variant="ghost" size="icon" aria-label={`Edit ${d.type==='meal'?d.meal:d.activity}`} onClick={edit}><Pencil size={16}/></Button><Button variant="ghost" size="icon" aria-label={`Remove ${d.type==='meal'?d.meal:d.activity}`} onClick={remove}><Trash2 size={16}/></Button></div></div>{d.type==='meal'?<ul>{d.items.map((item,i)=><li key={i}><span>{item.name}</span><small>{item.portion||'Portion not recorded'}{item.grams!==null&&item.portion!==`${item.grams} g`?` · ${amount(item.grams,'g')}`:''} · {item.certainty==='unknown'?'portion unknown':item.certainty==='estimated'?'portion estimated':'portion measured'}{!item.foodId?' · nutrients unknown':''}</small></li>)}</ul>:<p className="activity-detail">{d.minutes!==null?`${d.minutes} min`:'Duration unknown'} · {d.steps!==null?`${d.steps.toLocaleString()} steps`:'Steps not entered'} · {d.calories!==null?`${d.calories} kcal estimated`:'Calories unknown'}</p>}{d.notes&&<p className="entry-note">{d.notes}</p>}</article>;}
function NutrientTable({specs,summary}:{specs:NutrientSpec[];summary:NutritionSummary}){return <Table className="nutrient-table"><TableHeader><TableRow><TableHead>Nutrient</TableHead><TableHead>Known amount</TableHead><TableHead>Food coverage</TableHead><TableHead>Daily reference</TableHead></TableRow></TableHeader><TableBody>{specs.map(spec=>{const total=summary.nutrients[spec.id];return <TableRow key={spec.id}><TableCell><strong>{spec.name}</strong>{spec.note&&<small>{spec.note}</small>}</TableCell><TableCell>{amount(total?.value??null,spec.unit)}</TableCell><TableCell>{total?.covered??0} / {summary.items} foods</TableCell><TableCell>{spec.reference?amount(spec.reference,spec.unit):'—'}</TableCell></TableRow>;})}</TableBody></Table>;}

function MealEditor({initial,onSave,saving}:{initial?:MealData;onSave:(data:MealData)=>Promise<void>;saving:boolean}){
 const [meal,setMeal]=useState<MealData['meal']>(initial?.meal??'Breakfast');const [items,setItems]=useState<MealItem[]>(initial?.items??[]);const [notes,setNotes]=useState(initial?.notes??'');
 const [query,setQuery]=useState('');const [foods,setFoods]=useState<Food[]>([]);const [food,setFood]=useState<Food|null>(null);const [unlisted,setUnlisted]=useState(false);const [customName,setCustomName]=useState('');const [searchError,setSearchError]=useState('');const [searching,setSearching]=useState(false);
 const [quantity,setQuantity]=useState('100');const [unit,setUnit]=useState('grams');const [certainty,setCertainty]=useState('estimated');const [portionText,setPortionText]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(unlisted)return;const controller=new AbortController();const timer=setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/foods?q=${encodeURIComponent(query)}`,{signal:controller.signal});if(!r.ok)throw new Error();const result=await r.json() as {foods:Food[]};setFoods(result.foods);setSearchError('');}catch{if(!controller.signal.aborted)setSearchError('Food search is unavailable. Try again or add an unlisted food.');}finally{if(!controller.signal.aborted)setSearching(false);}},200);return()=>{clearTimeout(timer);controller.abort();};},[query,unlisted]);
 function addFood(){const name=unlisted?customName.trim():food?.name;if(!name){setError('Choose a food or enter its name.');return;}const portion=unit==='grams'?undefined:food?.portions[Number(unit)];const grams=certainty==='unknown'?null:Number(quantity)*(portion?.grams??1);if(grams!==null&&(!Number.isFinite(grams)||grams<=0||grams>10000)){setError('Enter a portion greater than 0 and no more than 10,000 grams.');return;}setItems([...items,{foodId:unlisted?null:food!.id,name,grams,portion:certainty==='unknown'?portionText.trim():(portion?`${quantity} × ${portion.label}`:`${quantity} g`),certainty:certainty as MealItem['certainty']}]);setError('');setFood(null);setQuery('');setCustomName('');setQuantity('100');setUnit('grams');setPortionText('');}
 return <form className="wellness-form" onSubmit={e=>{e.preventDefault();if(!items.length){setError('Add at least one food to this meal.');return;}void onSave({type:'meal',meal,items,notes});}}><Choice label="Meal" value={meal} onChange={v=>setMeal(v as MealData['meal'])} options={opts(['Breakfast','Lunch','Dinner','Snack'])}/>
  <div className="food-builder"><div className="food-builder-heading"><h3>Add a food</h3><Button type="button" variant="link" onClick={()=>{setUnlisted(!unlisted);setFood(null);setUnit('grams');setError('');}}>{unlisted?'Search USDA foods':'Use an unlisted food'}</Button></div>
   {unlisted?<label className="field"><span>Food name</span><Input placeholder="e.g. Homemade paneer curry" value={customName} maxLength={220} onChange={e=>setCustomName(e.target.value)}/><small>Saved for your record; nutrients remain unknown. You can log recipe ingredients separately.</small></label>:<div className="field"><label htmlFor="food-search">Search a reference food</label><Combobox items={foods} value={food} onValueChange={f=>{setFood(f);setUnit('grams');setQuantity('100');}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={f=>f.name} isItemEqualToValue={(a,b)=>a.id===b.id} filter={null}><ComboboxInput id="food-search" placeholder="Try cooked lentils, yogurt, oats…"/><ComboboxContent><ComboboxEmpty>{searching?'Searching…':'No match. Try fewer words or use an unlisted food.'}</ComboboxEmpty><ComboboxList>{(f:Food)=><ComboboxItem key={f.id} value={f}><span>{f.name}<small className="food-source">{f.source} · {f.release}</small></span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><small>Match the food and preparation, especially raw versus cooked.</small>{searchError&&<p className="form-error">{searchError}</p>}{food&&<p className="selected-food">Selected: {food.name}</p>}</div>}
   <Choice label="How certain is the portion?" value={certainty} onChange={setCertainty} options={[{value:'estimated',label:'Estimated — my best guess'},{value:'measured',label:'Measured — weighed or measured'},{value:'unknown',label:'Unknown — skip nutrient calculation'}]}/>
   {certainty==='unknown'?<label className="field"><span>Portion note (optional)</span><Input value={portionText} maxLength={120} onChange={e=>setPortionText(e.target.value)} placeholder="e.g. A bowl, not sure how much"/></label>:<div className="form-row"><label className="field"><span>Quantity</span><Input type="number" min="0.01" max="10000" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><Choice label="Unit" value={unit} onChange={v=>{setUnit(v);setQuantity(v==='grams'?'100':'1');}} options={[{value:'grams',label:'Grams'},...(food?.portions??[]).map((p,i)=>({value:String(i),label:`${p.label} (${p.grams} g)`}))]}/></div>}
   <Button type="button" variant="outline" onClick={addFood} disabled={items.length>=30||saving}><Plus size={16}/>Add food to meal</Button>
  </div>
  {items.length>0&&<div className="draft-foods"><h3>In this meal · {items.length}</h3>{items.map((item,i)=><div key={i}><span>{item.name}<small>{item.grams===null?'Portion unknown':amount(item.grams,'g')} · {item.foodId?'Reference estimate':'Nutrients unknown'}</small></span><Button type="button" variant="ghost" size="icon" aria-label={`Remove food ${i+1}`} onClick={()=>setItems(items.filter((_,j)=>j!==i))}><Trash2 size={16}/></Button></div>)}</div>}
  <label className="field"><span>Notes (optional)</span><Textarea value={notes} maxLength={1000} onChange={e=>setNotes(e.target.value)} placeholder="Anything you want to remember"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={saving} className="full-width">{saving?<Loader2 className="spinning"/>:<Check size={16}/>}Save meal</Button>
 </form>;
}

function WorkoutEditor({initial,onSave,saving}:{initial?:WorkoutData;onSave:(data:WorkoutData)=>Promise<void>;saving:boolean}){const [activity,setActivity]=useState(initial?.activity??'Walking');const [minutes,setMinutes]=useState(initial?.minutes?.toString()??'');const [steps,setSteps]=useState(initial?.steps?.toString()??'');const [calories,setCalories]=useState(initial?.calories?.toString()??'');const [notes,setNotes]=useState(initial?.notes??'');const [error,setError]=useState('');return <form className="wellness-form" onSubmit={e=>{e.preventDefault();if(!minutes&&!steps){setError('Enter minutes or steps.');return;}void onSave({type:'workout',activity,minutes:minutes?Number(minutes):null,steps:steps?Number(steps):null,calories:calories?Number(calories):null,notes});}}><label className="field"><span>Activity</span><Input required maxLength={80} value={activity} onChange={e=>setActivity(e.target.value)} placeholder="Walking, running, strength training…"/></label><div className="form-row"><label className="field"><span>Minutes</span><Input type="number" min="0.01" max="1440" step="any" value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder="e.g. 30"/></label><label className="field"><span>Steps</span><Input type="number" min="1" max="200000" step="1" value={steps} onChange={e=>setSteps(e.target.value)} placeholder="e.g. 3500"/></label></div><p className="muted-copy">Enter steps for this entry only. Don’t add a daily total again if those steps are already logged.</p><label className="field"><span>Calories burned (optional, kcal)</span><Input type="number" min="0" max="20000" step="any" value={calories} onChange={e=>setCalories(e.target.value)} placeholder="Estimate from your device or workout"/><small>This is your reported estimate, not a calculation by My Day Harbor.</small></label><label className="field"><span>Notes (optional)</span><Textarea maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={saving} className="full-width">{saving&&<Loader2 className="spinning"/>}Save activity</Button></form>;}

function GoalsEditor({initial,onSave,saving}:{initial:WellnessSettings;onSave:(settings:WellnessSettings)=>Promise<void>;saving:boolean}){const [settings,setSettings]=useState(initial);return <form className="wellness-form" onSubmit={e=>{e.preventDefault();void onSave(settings);}}><p className="muted-copy">Starting values use general FDA label references. They aren’t personalized prescriptions; needs vary. Use targets that fit your circumstances or professional guidance.</p><div className="goal-fields">{(['protein','fiber','magnesium'] as const).map((key,i)=><label className="field" key={key}><span>{MAIN[i].name} ({MAIN[i].unit}/day)</span><Input type="number" required min="1" max={[500,150,3000][i]} step="any" value={settings.targets[key]||''} onChange={e=>setSettings({...settings,targets:{...settings.targets,[key]:Number(e.target.value)}})}/></label>)}</div><Button type="button" variant="link" onClick={()=>setSettings({...settings,targets:{...DEFAULT_SETTINGS.targets}})}>Reset to general references</Button><Choice label="Meal suggestions" value={settings.diet} onChange={diet=>setSettings({...settings,diet:diet as WellnessSettings['diet']})} options={[{value:'any',label:'All foods'},{value:'vegetarian',label:'Vegetarian'},{value:'vegan',label:'Vegan'}]}/><fieldset><legend>Exclude from suggestions</legend><div className="allergen-options">{ALLERGENS.map(a=><label key={a}><Checkbox checked={settings.avoid.includes(a)} onCheckedChange={checked=>setSettings({...settings,avoid:checked?[...settings.avoid,a]:settings.avoid.filter(x=>x!==a)})}/>{a}</label>)}</div><p className="muted-copy">Filters cover these ingredients only. Other allergies, brands and cross-contact still need your attention.</p></fieldset><Button disabled={saving} type="submit" className="full-width">{saving&&<Loader2 className="spinning"/>}Save goals & preferences</Button></form>;}
